### ISSUE TITLE
Logout function not clearing ParseUser currentUser

### ISSUE THREAD

**Issue by israelmarmar** [parse-community/Parse-SDK-Flutter#384]
I am using parse_server_sdk: ^1.0.26 and I need to logout user on button click. it's working but when I call ParseUser.getcurrentUser() it's give me last logged in user instead of null.

**Comment by RodrigoSMarques** [comment]
Try this:
```dart
final ParseUser currentUser = await ParseUser.currentUser();
if (currentUser != null) 
      await currentUser.logout();
```

**Comment by israelmarmar** [comment]
I tried it, but it still doesn't clear currentUser.

**Comment by RodrigoSMarques** [comment]
You do not have any users logged in, otherwise ParseUser.currentUser () would return an object.

**Comment by maaeps** [comment]
I remember a similar issue. I think it was fixed.
Have you tried the not released version 1.0.27?

**Comment by israelmarmar** [comment]
I tried to use 1.0.27, but it still doesn't clear currentUser.

parse_server_sdk: 
    git:
      url: https://github.com/parse-community/Parse-SDK-Flutter.git
      ref: release/1.0.27

**Comment by fischerscode** [comment]
@israelmarmar 
Have you been able to solve this issue? Are we safe to close?
